import type { Generator, GeneratorInput, GeneratedArtifact } from './types'
import {
  toSnakeCase,
  toScreamingSnakeCase,
  mapCType,
  escapeCString,
} from './utils'

// ---------------------------------------------------------------------------
// C UAPI Header Generator
//
// Produces a Linux-kernel-style UAPI header for a Generic Netlink family.
// Follows Documentation/userspace-api/netlink/intro.rst conventions.
// ---------------------------------------------------------------------------

export class CHeaderGenerator implements Generator {
  readonly type = 'C_UAPI_HEADER' as const

  generate(input: GeneratorInput): GeneratedArtifact {
    const { schema, generatorVersion } = input
    const warnings: string[] = []

    const family = toSnakeCase(schema.family || schema.namespace || 'unknown')
    const FAMILY = toScreamingSnakeCase(family)
    const guardName = `_UAPI_LINUX_${FAMILY}_H`

    const lines: string[] = []

    // -----------------------------------------------------------------------
    // File header
    // -----------------------------------------------------------------------
    lines.push('/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */')
    lines.push(`/* Generated by KernelCanvas v${generatorVersion} — DO NOT EDIT */`)
    lines.push(`#ifndef ${guardName}`)
    lines.push(`#define ${guardName}`)
    lines.push('')
    lines.push('#include <linux/types.h>')
    lines.push('#include <linux/genetlink.h>')
    lines.push('')

    // -----------------------------------------------------------------------
    // Family name / version constants
    // -----------------------------------------------------------------------
    lines.push('/* ------------------------------------------------------------------ */')
    lines.push(`/* Family constants                                                    */`)
    lines.push('/* ------------------------------------------------------------------ */')
    lines.push('')
    lines.push(`#define ${FAMILY}_GENL_NAME   "${escapeCString(family)}"`)
    lines.push(`#define ${FAMILY}_GENL_VERSION 1`)
    lines.push('')

    // -----------------------------------------------------------------------
    // Command enum
    // -----------------------------------------------------------------------
    lines.push('/* ------------------------------------------------------------------ */')
    lines.push(`/* Commands                                                            */`)
    lines.push('/* ------------------------------------------------------------------ */')
    lines.push('')
    lines.push(`enum ${family}_command {`)
    lines.push(`\t${FAMILY}_CMD_UNSPEC,`)
    lines.push('')

    for (const cmd of schema.commands) {
      const CMD = toScreamingSnakeCase(cmd.name)
      if (cmd.description && cmd.description.trim() !== '') {
        lines.push(`\t/* ${cmd.description.trim()} */`)
      }
      if (cmd.deprecated) {
        lines.push(`\t/* DEPRECATED */`)
      }
      lines.push(`\t${FAMILY}_CMD_${CMD},`)
    }

    lines.push('')
    lines.push(`\t__${FAMILY}_CMD_MAX,`)
    lines.push(`\t${FAMILY}_CMD_MAX = __${FAMILY}_CMD_MAX - 1,`)
    lines.push(`};`)
    lines.push('')

    if (schema.commands.length === 0) {
      warnings.push('Schema has no commands — command enum will contain only UNSPEC.')
    }

    // -----------------------------------------------------------------------
    // Per-command attribute enums (request + response)
    // -----------------------------------------------------------------------
    lines.push('/* ------------------------------------------------------------------ */')
    lines.push(`/* Command attributes                                                  */`)
    lines.push('/* ------------------------------------------------------------------ */')
    lines.push('')

    for (const cmd of schema.commands) {
      const CMD = toScreamingSnakeCase(cmd.name)
      const cmd_snake = toSnakeCase(cmd.name)

      // Request attributes
      if (cmd.requestType && cmd.requestType.fields.length > 0) {
        lines.push(`/* Attributes for ${family}_${cmd_snake} request */`)
        lines.push(`enum ${family}_${cmd_snake}_req_attrs {`)
        lines.push(`\t${FAMILY}_${CMD}_REQ_ATTR_UNSPEC,`)
        lines.push('')
        for (const field of cmd.requestType.fields) {
          const FIELD = toScreamingSnakeCase(field.name)
          if (field.description && field.description.trim() !== '') {
            lines.push(`\t/* ${field.description.trim()} */`)
          }
          const qualifier = field.optional ? ' /* optional */' : ''
          const reserved = field.reserved ? ' /* reserved */' : ''
          lines.push(`\t${FAMILY}_${CMD}_REQ_ATTR_${FIELD},${qualifier}${reserved}`)
        }
        lines.push('')
        lines.push(`\t__${FAMILY}_${CMD}_REQ_ATTR_MAX,`)
        lines.push(`\t${FAMILY}_${CMD}_REQ_ATTR_MAX = __${FAMILY}_${CMD}_REQ_ATTR_MAX - 1,`)
        lines.push(`};`)
        lines.push('')
      }

      // Response attributes
      if (cmd.responseType && cmd.responseType.fields.length > 0) {
        lines.push(`/* Attributes for ${family}_${cmd_snake} response */`)
        lines.push(`enum ${family}_${cmd_snake}_rsp_attrs {`)
        lines.push(`\t${FAMILY}_${CMD}_RSP_ATTR_UNSPEC,`)
        lines.push('')
        for (const field of cmd.responseType.fields) {
          const FIELD = toScreamingSnakeCase(field.name)
          if (field.description && field.description.trim() !== '') {
            lines.push(`\t/* ${field.description.trim()} */`)
          }
          const qualifier = field.optional ? ' /* optional */' : ''
          const reserved = field.reserved ? ' /* reserved */' : ''
          lines.push(`\t${FAMILY}_${CMD}_RSP_ATTR_${FIELD},${qualifier}${reserved}`)
        }
        lines.push('')
        lines.push(`\t__${FAMILY}_${CMD}_RSP_ATTR_MAX,`)
        lines.push(`\t${FAMILY}_${CMD}_RSP_ATTR_MAX = __${FAMILY}_${CMD}_RSP_ATTR_MAX - 1,`)
        lines.push(`};`)
        lines.push('')
      }
    }

    // -----------------------------------------------------------------------
    // Multicast groups (one per event)
    // -----------------------------------------------------------------------
    if (schema.events.length > 0) {
      lines.push('/* ------------------------------------------------------------------ */')
      lines.push(`/* Multicast groups                                                    */`)
      lines.push('/* ------------------------------------------------------------------ */')
      lines.push('')
      lines.push(`enum ${family}_multicast_groups {`)
      for (const evt of schema.events) {
        const EVT = toScreamingSnakeCase(evt.name)
        if (evt.description && evt.description.trim() !== '') {
          lines.push(`\t/* ${evt.description.trim()} */`)
        }
        lines.push(`\t${FAMILY}_MCGRP_${EVT},`)
      }
      lines.push(`};`)
      lines.push('')

      // Multicast group name defines
      for (const evt of schema.events) {
        const EVT = toScreamingSnakeCase(evt.name)
        const evt_snake = toSnakeCase(evt.name)
        lines.push(`#define ${FAMILY}_MCGRP_${EVT}_NAME "${escapeCString(evt_snake)}"`)
      }
      lines.push('')
    }

    // -----------------------------------------------------------------------
    // Event payload attribute enums
    // -----------------------------------------------------------------------
    if (schema.events.length > 0) {
      lines.push('/* ------------------------------------------------------------------ */')
      lines.push(`/* Event payload attributes                                            */`)
      lines.push('/* ------------------------------------------------------------------ */')
      lines.push('')

      for (const evt of schema.events) {
        if (!evt.payloadType || evt.payloadType.fields.length === 0) continue

        const EVT = toScreamingSnakeCase(evt.name)
        const evt_snake = toSnakeCase(evt.name)

        lines.push(`/* Attributes for ${family}_${evt_snake} event payload */`)
        lines.push(`enum ${family}_${evt_snake}_attrs {`)
        lines.push(`\t${FAMILY}_${EVT}_ATTR_UNSPEC,`)
        lines.push('')
        for (const field of evt.payloadType.fields) {
          const FIELD = toScreamingSnakeCase(field.name)
          const qualifier = field.optional ? ' /* optional */' : ''
          lines.push(`\t${FAMILY}_${EVT}_ATTR_${FIELD},${qualifier}`)
        }
        lines.push('')
        lines.push(`\t__${FAMILY}_${EVT}_ATTR_MAX,`)
        lines.push(`\t${FAMILY}_${EVT}_ATTR_MAX = __${FAMILY}_${EVT}_ATTR_MAX - 1,`)
        lines.push(`};`)
        lines.push('')
      }
    }

    // -----------------------------------------------------------------------
    // Type definitions (enums, flags, structs)
    // -----------------------------------------------------------------------
    if (schema.typeDefs.length > 0) {
      lines.push('/* ------------------------------------------------------------------ */')
      lines.push(`/* Type definitions                                                    */`)
      lines.push('/* ------------------------------------------------------------------ */')
      lines.push('')

      for (const td of schema.typeDefs) {
        const td_snake = toSnakeCase(td.name)
        const TD = toScreamingSnakeCase(td.name)

        if (td.description && td.description.trim() !== '') {
          lines.push(`/* ${td.description.trim()} */`)
        }

        if (td.kind === 'ENUM') {
          lines.push(`enum ${family}_${td_snake} {`)
          for (const v of td.variants) {
            const V = toScreamingSnakeCase(v.name)
            const desc = v.description ? `\t/* ${v.description.trim()} */` : ''
            lines.push(`\t${FAMILY}_${TD}_${V} = ${v.value},${desc}`)
          }
          lines.push(`};`)
          lines.push('')
        } else if (td.kind === 'FLAGS') {
          // Flags: emit as #define bit-shift macros
          for (const v of td.variants) {
            const V = toScreamingSnakeCase(v.name)
            const desc = v.description ? `\t/* ${v.description.trim()} */` : ''
            lines.push(`#define ${FAMILY}_${TD}_${V}\t(1 << ${v.value})${desc}`)
          }
          lines.push('')
        } else if (td.kind === 'STRUCT' && td.fields.length > 0) {
          lines.push(`struct ${family}_${td_snake} {`)
          for (const field of td.fields) {
            const cType = mapCType(field.fieldType)
            const f_snake = toSnakeCase(field.name)
            const desc = field.description ? `\t/* ${field.description.trim()} */` : ''
            const reserved = field.reserved ? ' /* reserved */' : ''
            lines.push(`\t${cType} ${f_snake};${desc}${reserved}`)
          }
          lines.push(`} __attribute__((packed));`)
          lines.push('')
        } else if (td.kind === 'SCALAR' || td.kind === 'ALIAS') {
          if (td.fields.length > 0) {
            // Treat as a typedef'd struct
            lines.push(`typedef struct {`)
            for (const field of td.fields) {
              const cType = mapCType(field.fieldType)
              const f_snake = toSnakeCase(field.name)
              lines.push(`\t${cType} ${f_snake};`)
            }
            lines.push(`} ${family}_${td_snake}_t;`)
            lines.push('')
          } else {
            warnings.push(
              `Type '${td.name}' has kind ${td.kind} but no fields or variants — skipped.`,
            )
          }
        }
      }
    }

    // -----------------------------------------------------------------------
    // Permissions / capability constants
    // -----------------------------------------------------------------------
    if (schema.permissions.length > 0) {
      lines.push('/* ------------------------------------------------------------------ */')
      lines.push(`/* Required capabilities (informational)                               */`)
      lines.push('/* ------------------------------------------------------------------ */')
      lines.push('')
      for (const perm of schema.permissions) {
        const CAP = toScreamingSnakeCase(perm.capability)
        if (perm.description && perm.description.trim() !== '') {
          lines.push(`/* ${perm.description.trim()} */`)
        }
        const nsFlag = perm.namespaceAware ? ', namespace-aware' : ''
        lines.push(`/* Requires: ${perm.capability}${nsFlag} */`)
        lines.push(`#define ${FAMILY}_REQUIRES_${CAP} 1`)
        lines.push('')
      }
    }

    // -----------------------------------------------------------------------
    // Manual sections (for human-authored additions)
    // -----------------------------------------------------------------------
    lines.push('/* ------------------------------------------------------------------ */')
    lines.push(`/* BEGIN MANUAL SECTION extra_defines                                  */`)
    lines.push(`/* Add any supplemental #defines, typedefs, or inline helpers here.   */`)
    lines.push(`/* END MANUAL SECTION extra_defines                                    */`)
    lines.push('')

    // -----------------------------------------------------------------------
    // Include guard close
    // -----------------------------------------------------------------------
    lines.push(`#endif /* ${guardName} */`)
    lines.push('')

    return {
      filePath: `uapi/linux/${family}.h`,
      artifactType: 'C_UAPI_HEADER',
      content: lines.join('\n'),
      generatorVersion,
      warnings,
    }
  }
}
