import { Generator, GeneratorInput, GeneratedArtifact } from './types'
import { toSnakeCase, toScreamingSnakeCase } from './utils'

function mapToNlaType(fieldType: string): string {
  const typeMap: Record<string, string> = {
    u8: 'NLA_U8', u16: 'NLA_U16', u32: 'NLA_U32', u64: 'NLA_U64',
    s8: 'NLA_S8', s16: 'NLA_S16', s32: 'NLA_S32', s64: 'NLA_S64',
    string: 'NLA_NUL_STRING', binary: 'NLA_BINARY', flag: 'NLA_FLAG',
    bool: 'NLA_FLAG', nested: 'NLA_NESTED',
  }
  return typeMap[fieldType.toLowerCase()] || 'NLA_UNSPEC'
}

export class KernelScaffoldGenerator implements Generator {
  type = 'KERNEL_SCAFFOLD' as const

  generate(input: GeneratorInput): GeneratedArtifact {
    const { schema, generatorVersion } = input
    const family = toSnakeCase(schema.family)
    const FAMILY = toScreamingSnakeCase(schema.family)
    const lines: string[] = []

    lines.push(`// SPDX-License-Identifier: GPL-2.0`)
    lines.push(`/*`)
    lines.push(` * ${family}_genl.c - Generic Netlink interface for ${schema.family}`)
    lines.push(` * Generated by KernelCanvas v${generatorVersion}`)
    lines.push(` */`)
    lines.push(``)
    lines.push(`#include <linux/module.h>`)
    lines.push(`#include <linux/kernel.h>`)
    lines.push(`#include <net/genetlink.h>`)
    lines.push(`#include <linux/${family}.h>`)
    lines.push(``)

    for (const cmd of schema.commands) {
      const cmdSnake = toSnakeCase(cmd.name)
      const CMD = toScreamingSnakeCase(cmd.name)
      if (cmd.requestType && cmd.requestType.fields.length > 0) {
        lines.push(`static const struct nla_policy ${family}_${cmdSnake}_policy[] = {`)
        for (const field of cmd.requestType.fields) {
          if (field.reserved) continue
          const FIELD = toScreamingSnakeCase(field.name)
          lines.push(`\t[${FAMILY}_${CMD}_ATTR_${FIELD}] = { .type = ${mapToNlaType(field.fieldType)} },`)
        }
        lines.push(`};`)
        lines.push(``)
      }
    }

    for (const cmd of schema.commands) {
      const cmdSnake = toSnakeCase(cmd.name)
      lines.push(`static int ${family}_${cmdSnake}_doit(struct sk_buff *skb, struct genl_info *info)`)
      lines.push(`{`)
      lines.push(`\t/* BEGIN MANUAL SECTION ${cmdSnake}_handler */`)
      if (cmd.responseType) {
        lines.push(`\tstruct sk_buff *msg;`)
        lines.push(`\tvoid *hdr;`)
        lines.push(`\tmsg = genlmsg_new(NLMSG_DEFAULT_SIZE, GFP_KERNEL);`)
        lines.push(`\tif (!msg) return -ENOMEM;`)
        lines.push(`\thdr = genlmsg_put(msg, info->snd_portid, info->snd_seq,`)
        lines.push(`\t\t&${family}_family, 0, ${FAMILY}_CMD_${toScreamingSnakeCase(cmd.name)});`)
        lines.push(`\tif (!hdr) { nlmsg_free(msg); return -EMSGSIZE; }`)
        lines.push(`\tgenlmsg_end(msg, hdr);`)
        lines.push(`\treturn genlmsg_reply(msg, info);`)
      } else {
        lines.push(`\treturn -EOPNOTSUPP;`)
      }
      lines.push(`\t/* END MANUAL SECTION ${cmdSnake}_handler */`)
      lines.push(`}`)
      lines.push(``)
    }

    lines.push(`static const struct genl_ops ${family}_ops[] = {`)
    for (const cmd of schema.commands) {
      const cmdSnake = toSnakeCase(cmd.name)
      const CMD = toScreamingSnakeCase(cmd.name)
      const hasPolicy = cmd.requestType && cmd.requestType.fields.length > 0
      lines.push(`\t{`)
      lines.push(`\t\t.cmd = ${FAMILY}_CMD_${CMD},`)
      lines.push(`\t\t.doit = ${family}_${cmdSnake}_doit,`)
      if (hasPolicy) {
        lines.push(`\t\t.policy = ${family}_${cmdSnake}_policy,`)
        lines.push(`\t\t.maxattr = ${FAMILY}_${CMD}_ATTR_MAX,`)
      }
      if (cmd.privilegeRequirement) lines.push(`\t\t.flags = GENL_ADMIN_PERM,`)
      lines.push(`\t},`)
    }
    lines.push(`};`)
    lines.push(``)

    if (schema.events.length > 0) {
      lines.push(`static const struct genl_multicast_group ${family}_mcgrps[] = {`)
      for (const event of schema.events) {
        lines.push(`\t[${FAMILY}_MCGRP_${toScreamingSnakeCase(event.name)}] = { .name = "${toSnakeCase(event.name)}" },`)
      }
      lines.push(`};`)
      lines.push(``)
    }

    lines.push(`static struct genl_family ${family}_family = {`)
    lines.push(`\t.name\t\t= ${FAMILY}_GENL_NAME,`)
    lines.push(`\t.version\t= ${FAMILY}_GENL_VERSION,`)
    lines.push(`\t.ops\t\t= ${family}_ops,`)
    lines.push(`\t.n_ops\t\t= ARRAY_SIZE(${family}_ops),`)
    if (schema.events.length > 0) {
      lines.push(`\t.mcgrps\t\t= ${family}_mcgrps,`)
      lines.push(`\t.n_mcgrps\t= ARRAY_SIZE(${family}_mcgrps),`)
    }
    lines.push(`\t.module\t\t= THIS_MODULE,`)
    lines.push(`};`)
    lines.push(``)
    lines.push(`static int __init ${family}_init(void) { return genl_register_family(&${family}_family); }`)
    lines.push(`static void __exit ${family}_exit(void) { genl_unregister_family(&${family}_family); }`)
    lines.push(`module_init(${family}_init);`)
    lines.push(`module_exit(${family}_exit);`)
    lines.push(`MODULE_LICENSE("GPL");`)

    return {
      filePath: `${family}_genl.c`,
      artifactType: 'KERNEL_SCAFFOLD',
      content: lines.join('\n'),
      generatorVersion,
      warnings: schema.commands.filter(c => !c.requestType).map(c => `Command '${c.name}' has no request type`),
    }
  }
}
