import type { Generator, GeneratorInput, GeneratedArtifact } from './types'
import { toSnakeCase, escapeMarkdownCell } from './utils'

// ---------------------------------------------------------------------------
// Markdown Documentation Generator
//
// Produces comprehensive human-readable API documentation in Markdown format.
// Suitable for rendering in GitHub, GitLab, or static site generators.
// ---------------------------------------------------------------------------

export class MarkdownGenerator implements Generator {
  readonly type = 'MARKDOWN_DOCS' as const

  generate(input: GeneratorInput): GeneratedArtifact {
    const { schema, generatorVersion } = input
    const warnings: string[] = []
    const lines: string[] = []

    const family = toSnakeCase(schema.family || schema.namespace || 'unknown')
    const displayName = schema.family || schema.namespace || 'Unknown'

    // -----------------------------------------------------------------------
    // Header
    // -----------------------------------------------------------------------
    lines.push(`# ${displayName} API Documentation`)
    lines.push('')
    lines.push(`> **Generated by** KernelCanvas v${generatorVersion}  `)
    lines.push(`> **Schema version:** ${schema.version}  `)
    lines.push(`> **Generated at:** ${new Date().toISOString()}`)
    lines.push('')
    lines.push('---')
    lines.push('')

    // -----------------------------------------------------------------------
    // Overview
    // -----------------------------------------------------------------------
    lines.push('## Overview')
    lines.push('')
    if (schema.summary && schema.summary.trim() !== '') {
      lines.push(schema.summary.trim())
    } else {
      lines.push('_No summary provided._')
      warnings.push('Schema summary is empty — documentation overview will be sparse.')
    }
    lines.push('')

    // -----------------------------------------------------------------------
    // Transport
    // -----------------------------------------------------------------------
    lines.push('## Transport')
    lines.push('')
    lines.push(`| Property | Value |`)
    lines.push(`|----------|-------|`)
    lines.push(`| Transport | \`${escapeMarkdownCell(schema.transport)}\` |`)
    lines.push(`| Namespace / Family Name | \`${escapeMarkdownCell(schema.namespace)}\` |`)
    lines.push(`| Family Identifier | \`${escapeMarkdownCell(family)}\` |`)
    lines.push(`| Schema Version | ${schema.version} |`)
    lines.push('')

    if (schema.transport === 'GENERIC_NETLINK') {
      lines.push(
        'This API uses [Generic Netlink](https://docs.kernel.org/userspace-api/netlink/intro.html) ' +
        '(`NETLINK_GENERIC`) as its wire transport. Commands are dispatched through the `genl_family` ' +
        'registered under the family name above.',
      )
    } else if (schema.transport === 'IOCTL') {
      lines.push(
        'This API uses `ioctl(2)` as its wire transport. Commands are dispatched ' +
        `through the device node at \`${schema.namespace}\`.`,
      )
    } else if (schema.transport === 'CHAR_DEVICE') {
      lines.push(
        `This API uses a character device at \`${schema.namespace}\` as its wire transport.`,
      )
    }
    lines.push('')

    // -----------------------------------------------------------------------
    // Permissions
    // -----------------------------------------------------------------------
    if (schema.permissions.length > 0) {
      lines.push('## Required Permissions')
      lines.push('')
      lines.push('| Capability | Namespace-Aware | Description |')
      lines.push('|------------|:--------------:|-------------|')
      for (const perm of schema.permissions) {
        lines.push(
          `| \`${escapeMarkdownCell(perm.capability)}\` ` +
          `| ${perm.namespaceAware ? 'Yes' : 'No'} ` +
          `| ${escapeMarkdownCell(perm.description || '')} |`,
        )
      }
      lines.push('')
    }

    // -----------------------------------------------------------------------
    // Commands
    // -----------------------------------------------------------------------
    lines.push('## Commands')
    lines.push('')

    if (schema.commands.length === 0) {
      lines.push('_This schema defines no commands._')
      lines.push('')
      warnings.push('Schema has no commands.')
    } else {
      for (const cmd of schema.commands) {
        lines.push(`### \`${cmd.name}\``)
        lines.push('')

        if (cmd.deprecated) {
          lines.push('> **Deprecated.** This command should not be used in new code.')
          lines.push('')
        }

        if (cmd.description && cmd.description.trim() !== '') {
          lines.push(cmd.description.trim())
          lines.push('')
        }

        lines.push('| Property | Value |')
        lines.push('|----------|-------|')
        lines.push(`| Interaction Style | \`${escapeMarkdownCell(cmd.interactionStyle)}\` |`)
        lines.push(
          `| Privilege Requirement | ${cmd.privilegeRequirement ? `\`${escapeMarkdownCell(cmd.privilegeRequirement)}\`` : '_None_'} |`,
        )
        lines.push(`| Idempotent | ${cmd.idempotent ? 'Yes' : 'No'} |`)
        lines.push(`| Deprecated | ${cmd.deprecated ? 'Yes' : 'No'} |`)
        lines.push('')

        if (cmd.requestType) {
          lines.push('**Request Attributes**')
          lines.push('')
          lines.push(renderFieldTable(cmd.requestType.fields))
          lines.push('')
        } else {
          lines.push('**Request:** _No payload._')
          lines.push('')
        }

        if (cmd.responseType) {
          lines.push('**Response Attributes**')
          lines.push('')
          lines.push(renderFieldTable(cmd.responseType.fields))
          lines.push('')
        } else {
          lines.push('**Response:** _No payload._')
          lines.push('')
        }
      }
    }

    // -----------------------------------------------------------------------
    // Events
    // -----------------------------------------------------------------------
    lines.push('## Events')
    lines.push('')

    if (schema.events.length === 0) {
      lines.push('_This schema defines no events._')
      lines.push('')
    } else {
      for (const evt of schema.events) {
        lines.push(`### \`${evt.name}\``)
        lines.push('')

        if (evt.description && evt.description.trim() !== '') {
          lines.push(evt.description.trim())
          lines.push('')
        }

        lines.push('| Property | Value |')
        lines.push('|----------|-------|')
        lines.push(`| Subscription Model | \`${escapeMarkdownCell(evt.subscriptionModel)}\` |`)
        lines.push('')

        if (evt.payloadType && evt.payloadType.fields.length > 0) {
          lines.push('**Payload Attributes**')
          lines.push('')
          lines.push(renderEventFieldTable(evt.payloadType.fields))
          lines.push('')
        } else {
          lines.push('**Payload:** _No payload._')
          lines.push('')
        }
      }
    }

    // -----------------------------------------------------------------------
    // Types
    // -----------------------------------------------------------------------
    if (schema.typeDefs.length > 0) {
      lines.push('## Type Definitions')
      lines.push('')

      for (const td of schema.typeDefs) {
        lines.push(`### \`${td.name}\` (${td.kind})`)
        lines.push('')

        if (td.description && td.description.trim() !== '') {
          lines.push(td.description.trim())
          lines.push('')
        }

        if (td.kind === 'STRUCT' && td.fields.length > 0) {
          lines.push(renderFieldTable(td.fields))
          lines.push('')
        } else if ((td.kind === 'ENUM' || td.kind === 'FLAGS') && td.variants.length > 0) {
          lines.push('| Name | Value | Description |')
          lines.push('|------|------:|-------------|')
          for (const v of td.variants) {
            lines.push(
              `| \`${escapeMarkdownCell(v.name)}\` ` +
              `| ${v.value} ` +
              `| ${escapeMarkdownCell(v.description || '')} |`,
            )
          }
          lines.push('')
        } else if (td.kind === 'SCALAR' || td.kind === 'ALIAS') {
          if (td.fields.length > 0) {
            lines.push(renderFieldTable(td.fields))
            lines.push('')
          } else {
            lines.push('_Scalar or alias type — no fields._')
            lines.push('')
          }
        }
      }
    }

    // -----------------------------------------------------------------------
    // Footer
    // -----------------------------------------------------------------------
    lines.push('---')
    lines.push('')
    lines.push(
      `_This document was automatically generated from schema \`${schema.id}\` ` +
      `by KernelCanvas v${generatorVersion}. Do not edit manually._`,
    )
    lines.push('')

    return {
      filePath: `${family}-api.md`,
      artifactType: 'MARKDOWN_DOCS',
      content: lines.join('\n'),
      generatorVersion,
      warnings,
    }
  }
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

type StructField = {
  name: string
  fieldType: string
  optional: boolean
  reserved: boolean
  description: string
}

type EventField = {
  name: string
  fieldType: string
  optional: boolean
}

function renderFieldTable(fields: StructField[]): string {
  const rows: string[] = []
  rows.push('| Field | Type | Optional | Reserved | Description |')
  rows.push('|-------|------|:--------:|:--------:|-------------|')
  for (const f of fields) {
    rows.push(
      `| \`${escapeMarkdownCell(f.name)}\` ` +
      `| \`${escapeMarkdownCell(f.fieldType)}\` ` +
      `| ${f.optional ? 'Yes' : 'No'} ` +
      `| ${f.reserved ? 'Yes' : 'No'} ` +
      `| ${escapeMarkdownCell(f.description || '')} |`,
    )
  }
  return rows.join('\n')
}

function renderEventFieldTable(fields: EventField[]): string {
  const rows: string[] = []
  rows.push('| Field | Type | Optional |')
  rows.push('|-------|------|:--------:|')
  for (const f of fields) {
    rows.push(
      `| \`${escapeMarkdownCell(f.name)}\` ` +
      `| \`${escapeMarkdownCell(f.fieldType)}\` ` +
      `| ${f.optional ? 'Yes' : 'No'} |`,
    )
  }
  return rows.join('\n')
}
