import type { Generator, GeneratorInput, GeneratedArtifact } from './types'
import {
  toSnakeCase,
  toScreamingSnakeCase,
  toPascalCase,
  toCamelCase,
  mapTsType,
} from './utils'

// ---------------------------------------------------------------------------
// TypeScript Userspace Client Generator
//
// Produces a strongly-typed TypeScript client library for the kernel API.
// The client depends on a GenericNetlinkTransport abstraction that callers
// must supply — this keeps the generated code transport-agnostic and
// independently testable.
// ---------------------------------------------------------------------------

export class TsClientGenerator implements Generator {
  readonly type = 'TS_CLIENT' as const

  generate(input: GeneratorInput): GeneratedArtifact {
    const { schema, generatorVersion } = input
    const warnings: string[] = []

    const family = toSnakeCase(schema.family || schema.namespace || 'unknown')
    const FAMILY = toScreamingSnakeCase(family)
    const Family = toPascalCase(family)

    const lines: string[] = []

    // -----------------------------------------------------------------------
    // File header
    // -----------------------------------------------------------------------
    lines.push(`/* Generated by KernelCanvas v${generatorVersion} — DO NOT EDIT */`)
    lines.push(`/* Schema: ${schema.id}  version: ${schema.version} */`)
    lines.push(`/* Transport: ${schema.transport} */`)
    lines.push('')

    // -----------------------------------------------------------------------
    // Transport abstraction (ambient interface — callers implement this)
    // -----------------------------------------------------------------------
    lines.push('// ---------------------------------------------------------------------------')
    lines.push('// Transport abstraction')
    lines.push('//')
    lines.push('// Implement GenericNetlinkTransport against your preferred netlink library.')
    lines.push('// The generated client calls only this interface.')
    lines.push('// ---------------------------------------------------------------------------')
    lines.push('')
    lines.push('export interface GenericNetlinkTransport {')
    lines.push('  /** Send a command and wait for a response message. */')
    lines.push('  send<TReq, TRsp>(command: string, request: TReq): Promise<TRsp>')
    lines.push('  /**')
    lines.push('   * Subscribe to a multicast group.  Returns an unsubscribe function.')
    lines.push('   * The callback will be called for every notification received.')
    lines.push('   */')
    lines.push('  subscribe<TEvt>(group: string, callback: (event: TEvt) => void): () => void')
    lines.push('}')
    lines.push('')

    // -----------------------------------------------------------------------
    // Collect all named types we need to emit:
    //  1. typeDefs (structs, enums, flags, aliases)
    //  2. per-command request / response types
    //  3. per-event payload types
    // -----------------------------------------------------------------------

    const emittedTypes = new Set<string>()

    // Helper: emit a struct interface
    const emitInterface = (
      typeName: string,
      fields: Array<{ name: string; fieldType: string; optional: boolean; description?: string; reserved?: boolean }>,
    ) => {
      if (emittedTypes.has(typeName)) return
      emittedTypes.add(typeName)

      lines.push(`export interface ${typeName} {`)
      for (const field of fields) {
        const tsType = mapTsType(field.fieldType)
        const opt = field.optional ? '?' : ''
        const reserved = field.reserved ? ' // reserved' : ''
        const desc = field.description ? ` // ${field.description.trim()}` : ''
        lines.push(`  ${toCamelCase(field.name)}${opt}: ${tsType}${desc}${reserved}`)
      }
      lines.push(`}`)
      lines.push('')
    }

    // Helper: emit an enum type
    const emitEnum = (typeName: string, variants: Array<{ name: string; value: number; description: string }>) => {
      if (emittedTypes.has(typeName)) return
      emittedTypes.add(typeName)

      lines.push(`export enum ${typeName} {`)
      for (const v of variants) {
        const desc = v.description ? ` // ${v.description.trim()}` : ''
        lines.push(`  ${toPascalCase(v.name)} = ${v.value},${desc}`)
      }
      lines.push(`}`)
      lines.push('')
    }

    // Helper: emit a flags const object
    const emitFlags = (typeName: string, variants: Array<{ name: string; value: number; description: string }>) => {
      if (emittedTypes.has(typeName)) return
      emittedTypes.add(typeName)

      lines.push(`export const ${typeName} = {`)
      for (const v of variants) {
        const desc = v.description ? ` // ${v.description.trim()}` : ''
        lines.push(`  ${toPascalCase(v.name)}: 1 << ${v.value} as number,${desc}`)
      }
      lines.push(`} as const`)
      lines.push(`export type ${typeName}Flags = (typeof ${typeName})[keyof typeof ${typeName}]`)
      lines.push('')
    }

    // -----------------------------------------------------------------------
    // Section: typeDefs
    // -----------------------------------------------------------------------
    if (schema.typeDefs.length > 0) {
      lines.push('// ---------------------------------------------------------------------------')
      lines.push('// Schema-defined types')
      lines.push('// ---------------------------------------------------------------------------')
      lines.push('')
    }

    for (const td of schema.typeDefs) {
      const typeName = toPascalCase(td.name)
      if (td.description && td.description.trim() !== '') {
        lines.push(`/** ${td.description.trim()} */`)
      }

      switch (td.kind) {
        case 'STRUCT':
        case 'SCALAR':
        case 'ALIAS':
          if (td.fields.length > 0) {
            emitInterface(typeName, td.fields)
          } else {
            warnings.push(`Type '${td.name}' has kind ${td.kind} but no fields — emitted as unknown alias.`)
            if (!emittedTypes.has(typeName)) {
              emittedTypes.add(typeName)
              lines.push(`export type ${typeName} = unknown // no fields defined`)
              lines.push('')
            }
          }
          break

        case 'ENUM':
          emitEnum(typeName, td.variants)
          break

        case 'FLAGS':
          emitFlags(typeName, td.variants)
          break

        default:
          warnings.push(`Unknown type kind '${td.kind}' for type '${td.name}' — skipped.`)
      }
    }

    // -----------------------------------------------------------------------
    // Section: command request / response types
    // -----------------------------------------------------------------------
    if (schema.commands.length > 0) {
      lines.push('// ---------------------------------------------------------------------------')
      lines.push('// Command request and response types')
      lines.push('// ---------------------------------------------------------------------------')
      lines.push('')
    }

    for (const cmd of schema.commands) {
      const CmdPascal = toPascalCase(cmd.name)

      if (cmd.deprecated) {
        lines.push(`/** @deprecated ${cmd.description || cmd.name} */`)
      } else if (cmd.description && cmd.description.trim() !== '') {
        lines.push(`/** ${cmd.description.trim()} */`)
      }

      if (cmd.requestType) {
        emitInterface(`${CmdPascal}Request`, cmd.requestType.fields)
      }
      if (cmd.responseType) {
        emitInterface(`${CmdPascal}Response`, cmd.responseType.fields)
      }
    }

    // -----------------------------------------------------------------------
    // Section: event payload types
    // -----------------------------------------------------------------------
    if (schema.events.length > 0) {
      lines.push('// ---------------------------------------------------------------------------')
      lines.push('// Event payload types')
      lines.push('// ---------------------------------------------------------------------------')
      lines.push('')

      for (const evt of schema.events) {
        const EvtPascal = toPascalCase(evt.name)
        if (evt.description && evt.description.trim() !== '') {
          lines.push(`/** ${evt.description.trim()} */`)
        }
        if (evt.payloadType && evt.payloadType.fields.length > 0) {
          emitInterface(`${EvtPascal}Event`, evt.payloadType.fields.map(f => ({
            ...f,
            description: '',
            reserved: false,
          })))
        } else {
          if (!emittedTypes.has(`${EvtPascal}Event`)) {
            emittedTypes.add(`${EvtPascal}Event`)
            lines.push(`export type ${EvtPascal}Event = Record<string, never>`)
            lines.push('')
          }
        }
      }
    }

    // -----------------------------------------------------------------------
    // Client interface
    // -----------------------------------------------------------------------
    lines.push('// ---------------------------------------------------------------------------')
    lines.push(`// ${Family} client interface`)
    lines.push('// ---------------------------------------------------------------------------')
    lines.push('')
    lines.push(`export interface ${Family}Client {`)

    for (const cmd of schema.commands) {
      const CmdPascal = toPascalCase(cmd.name)
      const cmdCamel = toCamelCase(cmd.name)
      const reqType = cmd.requestType ? `${CmdPascal}Request` : 'void'
      const rspType = cmd.responseType ? `${CmdPascal}Response` : 'void'
      const reqParam = cmd.requestType ? `request: ${reqType}` : ''
      const deprecatedTag = cmd.deprecated ? '\n  /** @deprecated */' : ''
      const desc = cmd.description ? `  /** ${cmd.description.trim()} */\n` : ''
      lines.push(`${desc}${deprecatedTag}  ${cmdCamel}(${reqParam}): Promise<${rspType}>`)
    }

    for (const evt of schema.events) {
      const EvtPascal = toPascalCase(evt.name)
      const evtCamel = toCamelCase(evt.name)
      const desc = evt.description ? `  /** ${evt.description.trim()} */\n` : ''
      lines.push(
        `${desc}  on${EvtPascal}(callback: (event: ${EvtPascal}Event) => void): () => void`,
      )
    }

    lines.push(`}`)
    lines.push('')

    if (schema.commands.length === 0 && schema.events.length === 0) {
      warnings.push('Schema has no commands and no events — client interface will be empty.')
    }

    // -----------------------------------------------------------------------
    // Client factory function
    // -----------------------------------------------------------------------
    lines.push('// ---------------------------------------------------------------------------')
    lines.push(`// Client factory`)
    lines.push('// ---------------------------------------------------------------------------')
    lines.push('')
    lines.push(`export function create${Family}Client(`)
    lines.push(`  transport: GenericNetlinkTransport,`)
    lines.push(`): ${Family}Client {`)
    lines.push(`  return {`)

    for (const cmd of schema.commands) {
      const CmdPascal = toPascalCase(cmd.name)
      const cmdCamel = toCamelCase(cmd.name)
      const CMD = toScreamingSnakeCase(cmd.name)
      const hasReq = !!cmd.requestType
      const rspType = cmd.responseType ? `${CmdPascal}Response` : 'void'

      if (hasReq) {
        lines.push(
          `    async ${cmdCamel}(request) {`,
        )
        lines.push(
          `      return transport.send<${CmdPascal}Request, ${rspType}>('${FAMILY}_CMD_${CMD}', request)`,
        )
        lines.push(`    },`)
      } else {
        lines.push(`    async ${cmdCamel}() {`)
        lines.push(
          `      return transport.send<void, ${rspType}>('${FAMILY}_CMD_${CMD}', undefined as never)`,
        )
        lines.push(`    },`)
      }
    }

    for (const evt of schema.events) {
      const EvtPascal = toPascalCase(evt.name)
      const evtCamel = toCamelCase(evt.name)
      const EVT = toScreamingSnakeCase(evt.name)
      lines.push(`    on${EvtPascal}(callback) {`)
      lines.push(
        `      return transport.subscribe<${EvtPascal}Event>('${FAMILY}_MCGRP_${EVT}', callback)`,
      )
      lines.push(`    },`)
    }

    lines.push(`  }`)
    lines.push(`}`)
    lines.push('')

    return {
      filePath: `${family}-client.ts`,
      artifactType: 'TS_CLIENT',
      content: lines.join('\n'),
      generatorVersion,
      warnings,
    }
  }
}
